// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfQqMm9s2Iw9t79Xn-D0C6xSVE7l52lnI',
    appId: '1:887107830985:web:bfc498bb0f2283296ab918',
    messagingSenderId: '887107830985',
    projectId: 'love-relationship-7c9ad',
    authDomain: 'love-relationship-7c9ad.firebaseapp.com',
    storageBucket: 'love-relationship-7c9ad.firebasestorage.app',
    measurementId: 'G-E21XVRRGN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM6S8g5VelI1irxuKAFSm_6Vi5jsBwR2s',
    appId: '1:887107830985:android:55e5fbdcbe42b1496ab918',
    messagingSenderId: '887107830985',
    projectId: 'love-relationship-7c9ad',
    storageBucket: 'love-relationship-7c9ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACHH0h15K8SwHjs5FIj2qlBoKkp0zbzbo',
    appId: '1:887107830985:ios:2c94b293977ab9fb6ab918',
    messagingSenderId: '887107830985',
    projectId: 'love-relationship-7c9ad',
    storageBucket: 'love-relationship-7c9ad.firebasestorage.app',
    iosBundleId: 'com.always.about.love.loveRelationship',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACHH0h15K8SwHjs5FIj2qlBoKkp0zbzbo',
    appId: '1:887107830985:ios:2c94b293977ab9fb6ab918',
    messagingSenderId: '887107830985',
    projectId: 'love-relationship-7c9ad',
    storageBucket: 'love-relationship-7c9ad.firebasestorage.app',
    iosBundleId: 'com.always.about.love.loveRelationship',
  );
}
