// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// Run `flutterfire configure` to regenerate with your project's Firebase config.

import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM6S8g5VelI1irxuKAFSm_6Vi5jsBwR2s',
    appId: '1:887107830985:android:55e5fbdcbe42b1496ab918',
    messagingSenderId: '887107830985',
    projectId: 'love-relationship-7c9ad',
    storageBucket: 'love-relationship-7c9ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyReplaceWithRealFromFirebaseConsole',
    appId: '1:887107830985:ios:2c94b293977ab9fb6ab918',
    messagingSenderId: '887107830985',
    projectId: 'love-relationship-7c9ad',
    storageBucket: 'love-relationship-7c9ad.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyReplaceWithRealFromFirebaseConsole',
    appId: '1:887107830985:ios:2c94b293977ab9fb6ab918',
    messagingSenderId: '887107830985',
    projectId: 'love-relationship-7c9ad',
    storageBucket: 'love-relationship-7c9ad.firebasestorage.app',
  );
}
